server:
  name: "CodeCompass"
  version: "1.0.0"
  max_file_size_mb: 10
  max_search_results: 1000
  default_encoding: "utf-8"

repositories:
  roots: []
  ignore_patterns:
    - "**/node_modules/**"
    - "**/.git/**"
    - "**/__pycache__/**"
    - "**/*.pyc"
    - "**/dist/**"
    - "**/build/**"
    - "**/.venv/**"
    - "**/venv/**"
    - "**/.pytest_cache/**"
    - "**/coverage/**"
    - "**/.coverage"
    - "**/htmlcov/**"
    - "**/.mypy_cache/**"
    - "**/.tox/**"
    - "**/target/**"
    - "**/Cargo.lock"
    - "**/package-lock.json"
    - "**/yarn.lock"
    - "**/Pipfile.lock"
    - "**/poetry.lock"

search:
  default_limit: 50
  max_limit: 1000
  case_sensitive: false
  include_binary: false
  file_extensions:
    - "*.py"
    - "*.js"
    - "*.ts"
    - "*.jsx"
    - "*.tsx"
    - "*.java"
    - "*.cpp"
    - "*.c"
    - "*.h"
    - "*.go"
    - "*.rs"
    - "*.php"
    - "*.rb"
    - "*.swift"
    - "*.kt"
    - "*.scala"
    - "*.r"
    - "*.m"
    - "*.sh"
    - "*.bash"
    - "*.zsh"
    - "*.fish"
    - "*.ps1"
    - "*.bat"
    - "*.cmd"
    - "*.sql"
    - "*.html"
    - "*.css"
    - "*.scss"
    - "*.sass"
    - "*.less"
    - "*.xml"
    - "*.json"
    - "*.yaml"
    - "*.yml"
    - "*.toml"
    - "*.ini"
    - "*.cfg"
    - "*.conf"
    - "*.md"
    - "*.rst"
    - "*.txt"
    - "*.log"

semantic_search:
  enabled: true
  model: "all-MiniLM-L6-v2"
  chunk_size: 512
  chunk_overlap: 50
  index_path: "./indexes"
  rebuild_threshold_hours: 24

todos:
  patterns:
    - "TODO"
    - "FIXME"
    - "HACK"
    - "NOTE"
    - "XXX"
    - "BUG"
  case_sensitive: false

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/server.log"
